### PR TITLE
Fixed "No Post Revision" in phpBB.

### PR DESCRIPTION
**Pull request by Dark1z**
- [x] Fixed mismatched post edit time, reason & user on bottom of post & Current Post in Revision history.

### CODE REVIEW

**Comment by Dark1z** [comment]
Here is mismatches in details :

Post Revisions : 


Post : 


and the Reason should be `test 1` & not `test 10` , also the time should be same as the one from reason  `test 1`.
the mismatches & the history trace kept in phpBB post table is same data , which supposed to be deleted & replaced by previous one.

Best regards 👍

**Comment by Dark1z** [comment]
Now , the details will match in post revision history.

**Comment by primehalo** [comment]
I was looking over it and I don't understand this part:
```
		if ($this->revision_skipped)
		{
			$key_to_unset	= array_search('post_edit_count = post_edit_count + 1', $sql_data[POSTS_TABLE]['stat']);
			unset($sql_data[POSTS_TABLE]['stat'][$key_to_unset]);
			unset($sql_data[POSTS_TABLE]['sql']['post_edit_user']);
			unset($sql_data[POSTS_TABLE]['sql']['post_edit_reason']);
			unset($sql_data[POSTS_TABLE]['sql']['post_edit_time']);
		}
```
Maybe it's because I'm quite tired at the moment, but isn't this removing the basic edit info for the active post? We shouldn't be changing what phpbb saves by default. If this extension gets removed, the edit info shown on the post should be shown exactly as if this extension never existed at all.

I was thinking that the only change we needed to fix this bug was to change this:
```
		// Obtain the current version of the post as well as data for the last person to edit it
		$sql = $this->db->sql_build_query('SELECT', array(
			'SELECT'	=> 'p.forum_id, p.poster_id, p.post_time, p.post_subject, p.post_text, p.primepost_edit_time,
							p.post_edit_reason, p.primepost_edit_user, p.primepost_edit_count, p.bbcode_bitfield, p.bbcode_uid, u.*',
			'FROM'		=> array(POSTS_TABLE => 'p'),
			'LEFT_JOIN'	=> array(
				array(
					'FROM'	=> array(USERS_TABLE => 'u'),
					'ON'	=> '(p.primepost_edit_user = 0 AND p.poster_id = u.user_id) OR p.primepost_edit_user = u.user_id',
				),
			),
			'WHERE'		=> "p.post_id = {$post_id}",
		));
```
to this:
```
		// Obtain the current version of the post as well as data for the last person to edit it
		// The post_edit_* fields hold the data for the most recent edit, but we need them as primepost_* for when this post gets merged into the array of revisions.
		$sql = $this->db->sql_build_query('SELECT', array(
			'SELECT'	=> 'p.forum_id, p.poster_id, p.post_time, p.post_subject, p.post_text, p.post_edit_time AS primepost_edit_time,
							p.post_edit_reason, p.post_edit_user AS primepost_edit_user, p.post_edit_count, p.bbcode_bitfield, p.bbcode_uid, u.*',
			'FROM'		=> array(POSTS_TABLE => 'p'),
			'LEFT_JOIN'	=> array(
				array(
					'FROM'	=> array(USERS_TABLE => 'u'),
					'ON'	=> '(p.post_edit_user = 0 AND p.poster_id = u.user_id) OR p.post_edit_user = u.user_id',
				),
			),
			'WHERE'		=> "p.post_id = " . (int)$post_id,
		));
```

**Comment by Dark1z** [comment]
Kindly check the lastest commit, this thing is no longer there.
> ```
> 		if ($this->revision_skipped)
> 		{
> 			$key_to_unset	= array_search('post_edit_count = post_edit_count + 1', $sql_data[POSTS_TABLE]['stat']);
> 			unset($sql_data[POSTS_TABLE]['stat'][$key_to_unset]);
> 			unset($sql_data[POSTS_TABLE]['sql']['post_edit_user']);
> 			unset($sql_data[POSTS_TABLE]['sql']['post_edit_reason']);
> 			unset($sql_data[POSTS_TABLE]['sql']['post_edit_time']);
> 		}
>```
Above part is removed.
Check commit : https://github.com/primehalo/primepostrevisions/pull/19/commits/a13349b7a8cc439954e72d2a5fae4d26fac3d55b

It will do as it used to do before , but now also for skipping the revision.

Best regards 👍

**Comment by primehalo** [comment]
Was that removed 3 days ago? I was just looking at it last night, I guess I had an old commit or something. I was using GitHub desktop, not looking at it in the web browser. Anyway, I just pushed the changed I mentioned earlier to the master branch. This shows the correct edit info for the most recent post on the post revisions page. 

I was thinking we should add `↩` in front of the "View the latest post" link, but to keep it safe with RTL languages we should add it via CSS ::before `content: "↩ ";` instead of putting it directly in the template. 
Clipboard01

Do you think we should add a message after the "_**This page shows all versions...**_" text that tells how many total edits and how many revisions there are? Something like "_**Edited 4 times in total. Showing 2 saved revision.**_", "_**Total Edits: 4, Saved Revisions: 2**_", or "_**Saved revisions: 2 out of 4 total edits**_"?

**Comment by Dark1z** [comment]
> Was that removed 3 days ago? I was just looking at it last night, I guess I had an old commit or something. I was using GitHub desktop, not looking at it in the web browser. Anyway, I just pushed the changed I mentioned earlier to the master branch. This shows the correct edit info for the most recent post on the post revisions page.

In that case , I am closing this PR.

further discussions here : 
- https://github.com/primehalo/primepostrevisions/issues/20
- https://github.com/primehalo/primepostrevisions/issues/21

Best regards 👍

**Comment by primehalo** [comment]
Do you have time to look at the Prime Post Revisions recent issue? I'm 
recovering from eye surgery and am unable to see computer screens very 
well yet.

**Comment by Dark1z** [comment]
> Do you have time to look at the Prime Post Revisions recent issue? I'm recovering from eye surgery and am unable to see computer screens very well yet.

I wish you a healthy recovery.

Currently there is one issue and one pull request,
The issue is "Post edit time is same for all revisions" made on 2nd of April,
and the PR is for the support of a new style made on 26th of May.

I have started to work and I reach home quite late,
I do not get any extra time daily unlike before when I used to be student,
I'll see if I can make some time on Sundays and check that issue.

Best regards 👍

**Comment by primehalo** [comment]
Thanks. I really didn't expect recovery to take this long and it's quite 
frustrating.

**Comment by primehalo** [comment]
I took a look at the edit time issue today. I believe the issue is that 
the first post shown in the list of revisions is actually the current 
post, not one from the revisions table, and it doesn't save the 
/post_edit_time/ unless there is a /post_edit_reason/ 
(/includes/functions_posting.php/ around line #1790):
             // Display edit info if edit reason given or user is 
editing his post, which is not the last within the topic.
             if ($data_ary['post_edit_reason'] || 
(!$auth->acl_get('m_edit', $data_ary['forum_id']) && ($post_mode == 
'edit' || $post_mode == 'edit_first_post')))
             {
                 $data_ary['post_edit_reason']        = 
truncate_string($data_ary['post_edit_reason'], 255, 255, false);

                 $sql_data[POSTS_TABLE]['sql']    = array(
                     'post_edit_time'    => $current_time,
                     'post_edit_reason'    => $data_ary['post_edit_reason'],
                     'post_edit_user'    => (int) 
$data_ary['post_edit_user'],
                 );

                 $sql_data[POSTS_TABLE]['stat'][] = 'post_edit_count = 
post_edit_count + 1';
             }
             else if (!$data_ary['post_edit_reason'] && $mode == 'edit' 
&& $auth->acl_get('m_edit', $data_ary['forum_id']))
             {
                 $sql_data[POSTS_TABLE]['sql'] = array(
                     'post_edit_reason'    => '',
                 );
             }
So I think the fix would be to save this /post_edit_time/ no matter what 
in /event/listener.php update_edit_data($event)/:
         if (empty($sql_data[POSTS_TABLE]['sql']['post_edit_time'])) {
             $sql_data[POSTS_TABLE]['sql']['post_edit_time'] = $cur_time;
         }
Have you had a chance to look at this issue? If so, did you come to the 
same conclusion?

**Comment by Dark1z** [comment]
> I took a look at the edit time issue today. I believe the issue is that the first post shown in the list of revisions is actually the current post, not one from the revisions table, and it doesn't save the /post_edit_time/ unless there is a /post_edit_reason/ (/includes/functions_posting.php/ around line #1790):             // Display edit info if edit reason given or user is editing his post, which is not the last within the topic.             if ($data_ary['post_edit_reason'] || (!$auth->acl_get('m_edit', $data_ary['forum_id']) && ($post_mode == 'edit' || $post_mode == 'edit_first_post')))             {                 $data_ary['post_edit_reason']        = truncate_string($data_ary['post_edit_reason'], 255, 255, false);                 $sql_data[POSTS_TABLE]['sql']    = array(                     'post_edit_time'    => $current_time,                     'post_edit_reason'    => $data_ary['post_edit_reason'],                     'post_edit_user'    => (int) $data_ary['post_edit_user'],                 );                 $sql_data[POSTS_TABLE]['stat'][] = 'post_edit_count = post_edit_count + 1';             }             else if (!$data_ary['post_edit_reason'] && $mode == 'edit' && $auth->acl_get('m_edit', $data_ary['forum_id']))             {                 $sql_data[POSTS_TABLE]['sql'] = array(                     'post_edit_reason'    => '',                 );             } So I think the fix would be to save this /post_edit_time/ no matter what in /event/listener.php update_edit_data($event)/:         if (empty($sql_data[POSTS_TABLE]['sql']['post_edit_time'])) {             $sql_data[POSTS_TABLE]['sql']['post_edit_time'] = $cur_time;         } Have you had a chance to look at this issue? If so, did you come to the same conclusion?

Replied on discord.

**Pull request closed without merging**
