### PR TITLE
Comparisons of 2 Revisions

### PR DESCRIPTION
**Pull request by Dark1z**
Add the ability for Comparisons of selected Revisions.

Working : 
If 0 selection of Revision is done , then produce an Err0r.
If 1 selection of Revision is done , then compare selected revision with current Post.
If 2 or more selection of Revisions is done , then compare all selected revision.
~~If 3 or more selection of Revisions is done , then compare Max & Min revision using ID.~~

On Viewing Page : 

On Comparisons of 2 Revisions Page : 

I have added all Lang Keys in other Lang Files.

I hope you like it.
If any changes are required , then let me know.

Best regards 👍

### CODE REVIEW

**Comment by primehalo** [comment]
Why limit it to comparing only two revisions? Couldn't it be set to display and compare all checked revisions?

**Comment by Dark1z** [comment]
Goal is to differentiate 2 far off revisions.

**Comment by Dark1z** [comment]
Say we have revisions from 1 to 10 .

I want the difference between 3rd & 8th ...
Select 3rd & 8th , click the button.
This gives diff between 2 far off revisions.

Now , you want difference between 2nd, 4th & 6th ...
Select 2nd & 6th , click the button.
It will show the diff between 2nd & 6th , coz the diff is already included in 6th revision.

I hope you understand now.

Best regards 👍

**Comment by dark-1** [comment]
Done as you asked in Discord 😃 

Best regards 👍

**Comment by Dark1z** [comment]
Done as you asked in Discord 😃

Best regards 👍

**Comment by primehalo** [comment]
In body.html, the button to compare selected revisions is inside `{% if DELETABLE_CNT > 1 %} {% endif %}`. We would always want the compare button to show up so that check should be moved inside the fieldset to only affect the delete button. Perhaps we should use JavaScript to disable both buttons when none of the checkboxes are selected?

**Comment by Dark1z** [comment]
I did some slight changes and also added URL to previous page in comparison mode.

Now , what should we do for comparision of `Current Post` ?
In current system , If 1 selection of Revision is done , then compares selected revision with current Post.

What do you propose ?
Add a selection box to it {having value `0`} ??
Check for that value `0` & ignore it during deletion of revision ???

Best regards 👍

**Comment by primehalo** [comment]
I think `'COMPARISONS'		=> ($revision_id !== false) ? false : true,` might be better written as `'COMPARISONS'		=> ($revision_id === false),`. You changed `$deletable_cnt` to `$selectable_cnt` which makes sense, but then `$selectable_cnt	+= $delete_url ? 1 : 0;` is only accurate when in the selected comparison mode where the checkbox is only displayed for deletion purposes. In the regular post history mode, the count will be wrong if the user doesn't have the permissions to delete revisions.

As for the current post... currently if only one post is selected for compare then only that post is showing up, not that post and the current post. So something is wrong there. Putting that aside, I only see two options, either always include the current post or add a checkbox to make it selectable. If we add the checkbox then I'd want to display an error message when trying to delete rather than just ignoring it and deleting all other checked revisions (both JavaScript and PHP error handling). That would also make using the Check All box a bit more annoying since they'd have to manually uncheck the current post when trying to delete all revisions. 

My vote would be for always showing the current post as I can't see it hurting anything by being there, it'd be less work to implement, and less confusing/annoying for someone trying to delete all revisions. But I'm open to opinions and suggestions.

**Comment by Dark1z** [comment]
Wait ! the delete & view permission is separate. {Sorry , I forgot about that.}
so we will need to add one more checkbox for selecting for compare ,
coz user with view permission but not delete permission won't be able to compare ...
I'll proceed making the above changes...

I'll revert `$selectable_cnt` to `$deletable_cnt` ...
also I'll do `'COMPARISONS' => ($revision_id === false)` ..

BR 👍

**Comment by Dark1z** [comment]
@primehalo ,

I have done the above said changes.

Since User may have View permission but not Delete permission,
So previously the user was not able to see checkboxes,
Now they will be able to see them. 

DO NOT MERGE yet , I have to do one more thing...

BR 👍

**Comment by Dark1z** [comment]
@primehalo ,

I think this PR is ready to merge.
Kindly review it , please.

BR 👍

**Comment by Dark1z** [comment]
Update to show the difference from the First comment of mine to current : 

View Mode : 


Compare Mode : 


BR 👍

**Comment by primehalo** [comment]
I did some bug fixes and some style changes. I noticed another bug while testing in responsive mode that I don't have time to look into right now. The button icons for each post are replaced with a single ellipse button "..." which when clicked is supposed to show a list of the buttons but in text for with icons, however this list is not showing up correctly.

**Comment by Dark1z** [comment]
> ... I noticed another bug while testing in responsive mode that I don't have time to look into right now. The button icons for each post are replaced with a single ellipse button "..." which when clicked is supposed to show a list of the buttons but in text for with icons, however this list is not showing up correctly.

I have fixed this.

BUT can you do a jQuery or JS or `onClick` attribute to check the box on clicking the respective Icon ???
I tried but failed... 😢 

BR 👍

**Comment by Dark1z** [comment]
I removed the responsiveness from those Checkboxes , which solved all the problems...
Also fixed the Buttons issues.

I think this needs to be merged. 

BR 👍

**Comment by Dark1z** [comment]
Did the changes & merged as discussed in Discord.

BR 👍

**Pull request merged**
